language: node_js
node_js:
  - "5.7"
  - "4.4"
  - "0.12"
script: npm run cover
matrix:
  allow_failures:
    - node_js: "5.7" # for node-sass error

before_script:
  - npm install coveralls

after_success:
  - cat ./coverage/lcov.info | ./node_modules/.bin/coveralls --verbose
  - rm -rf ./coverage
